#!/usr/bin/env bash
# This script installs the nginx server with the configuration
#+ Listens on port 80.



apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html' 
service nginx restart
