#!/bin/bash
ls -1pa | grep -v '^\./$' | grep -v '^../$' | awk '{print (NF && $0 ~ /\/$/ ? $0 : $0 "/")}' | LC_COLLATE=C sort -k1.2 | awk 'BEGIN {printf "./, ../, "} {printf "%s, ", $0}' | sed 's/, $/\n/'
