#!/bin/bash
find . -maxdepth 1 -mindepth 1 \( -type d -printf '%p/,' -o -type f -printf '%p,' \) | LC_COLLATE=C sort -k1.2 | awk 'BEGIN {printf "./, ../, "} {gsub(/^\.\//, ""); printf "%s", $0} END {print ""}'
