#!/usr/bin/env bash
# This script executes the following:
#   Create a file /var/run/myscript.pid containing the PID script.
#   Displays "To infinity and beyond" temporarily
#   Display "I hate the kill command" after receiving a SIGTERM
#   Display "Y U no love me?!" after receiving a SIGINT
#   Deletes the file /var/run/myscript.pid and stops running after
#+  receiving a SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUITgit 
done
