#!/usr/bin/env bash
# Script that kills all scripts with specific name

PID=$(pgrep -f 4-to_infinity_and_beyond)

if [ -n "$PID" ]; then
  xkill -PID $PID
  echo "Process stopped successfully."
else
  echo "Process not found."
fi
