#!/usr/bin/env bash
# This bash script displays
# the contents of a current directory
# in the list format
# with only part of the filenames after the first dash
list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
