#!/usr/bin/env bash
# This bash script will install the ufw firewall and setup a few rules on my web-01 server.

sudo apt install -y ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
echo "y" | sudo ufw enable
