#!/usr/bin/env bash
# This bash script installs the ufw firewall and setups rules on my web-01 server.

sudo apt install -y ufw
sudo sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw disable
sudo ufw enable
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
echo "y" | sudo ufw enable
